### ISSUE TITLE
Document dependency overrides using `uv`

### ISSUE THREAD

**Issue by hkoller** [ait-energy/iesopt#68]
Documentation is outdated and could be improved in some places:

**uv instead of Poetry**
Project examples should use uv instead of poetry. 

**Mention how to override the Julia version**
In an uv project the Julia version, iesopt depends on, can be changed like so:

```toml

dependencies = [
    "iesopt >= 2.4.1",
]

[tool.uv]
override-dependencies = [
  "juliacall == 0.9.24",
  "juliapkg == 0.1.15"
]
```
